### ISSUE TITLE
Generated .orcacosmo file for methanol doesn't match .orcacosmo file in the openCOSMO-RS_py repository

### ISSUE THREAD

**Issue by DiegoTMelfi** [TUHH-TVT/openCOSMO-RS_conformer_pipeline#5]
Hi,

I am using windows and orca 5.0.4. 

I am able to execute the ConformerGenerator.py and retrieve the substance_c000.orcacosmo file. 

To confirm if everything is working as it should, I used the cosmo_visualizations.plot_sigmaprofiles function from the openCOSMO-RS_py repository to compare the sigma profile calculated from the .orcacosmo file that I generated for methanol (smiles CO, charge 0) in my system to the sigma profile calculated for methanol with the .orcacosmo files for methanol in the [tests folder of the openCOSMO-RS_py repository](https://github.com/TUHH-TVT/openCOSMO-RS_py/tree/master/tests/COSMO_ORCA/CH4O_001_methanol/COSMO_TZVPD).

Sigma profile for methanol calculated from .orcacosmo file generated in my system using ConformerGenerator.py:
![image](https://github.com/TUHH-TVT/openCOSMO-RS_conformer_pipeline/assets/106633256/b7129ce5-1982-40cf-bbfb-58e61adab1cc)

Sigma profile for methanol calculated from .orcacosmo file available in the [tests folder of the openCOSMO-RS_py repository](https://github.com/TUHH-TVT/openCOSMO-RS_py/tree/master/tests/COSMO_ORCA/CH4O_001_methanol/COSMO_TZVPD)
![image](https://github.com/TUHH-TVT/openCOSMO-RS_conformer_pipeline/assets/106633256/444394a6-9bf4-4033-8b2e-b1b0a5afcf04):

As shown, the profiles don't match exactly. 

Were the files in the [tests folder of the openCOSMO-RS_py repository](https://github.com/TUHH-TVT/openCOSMO-RS_py/tree/master/tests/COSMO_ORCA/CH4O_001_methanol/COSMO_TZVPD) generated with the current ConformerGenerator.py? If yes, do you happen to have any insight on where the differences could be coming from?

**Comment by simonmb** [comment]
Hi Diego, thank you for opening an issue on this topic. You are actually not the first one to notice this. Unfortunately, different ORCA versions might lead to different sigma profile. The difference should not be huge. However, specifically, we have been working with them to improve the output of the ORCA CPCM calculations. We are currently working on a paper with the new upcoming ORCA release. I would update the example files and leave the issue open till then. If you are interested in a more detailed comparison drop me an email on my university email address.

**Comment by DiegoTMelfi** [comment]
Hi Simon,

Thanks for replying so quickly! I just sent you an e-mail.

**Comment by simonmb** [comment]
Hi, I just updated the orcacosmo files in the bindings folder to the newest version. They should now match yours much better.
