### ISSUE TITLE
Missing cpcm_radii.inp

### ISSUE THREAD

**Issue by kainszs** [TUHH-TVT/openCOSMO-RS_conformer_pipeline#6]
Hello,
I saw that you removed the CPCM radii from `Generate_Conformers.py`. Are you using different radii in cpcm_radii.inp than the previously hardcoded ones?

Best regards, Kai

**Comment by simonmb** [comment]
I wanted users to have the flexibility to change the radii. We might also change them in the future. However, I just added the radii file so it can be used with the pipeline, containing the radii I have used so far. These are not optimized by any means, but the latest version of openCOSMO-RS (soon to be submitted) will be using these.
