### ISSUE TITLE
about input.dat of  orca in step  "21_ORCA_DFT_CPCM_final", the key word "cut_area" error.

### ISSUE THREAD

**Issue by WangMM2** [TUHH-TVT/openCOSMO-RS_conformer_pipeline#7]
The keyword "cut_area" in lines 965-967 (openCOSMO-RS_conformer_pipeline) is not displayed in orca5.0.4 .  The error information is as follows,
'''
[file orca_tools/Tool-Scanner/qcscan1.cpp, line 102]: 
	 Unknown identifier in CPCM block line   24  : 
	 Last token : CUT_AREA
'''
Only when I comment out these lines (965-967) of code, the program will work. 
What is the specific meaning of this value? Will it matter if i ignore the "cut_area"?

**Comment by simonmb** [comment]
Hi @WangMM2, what you did is a quick fix that should not change the output too much. This version of the conformer pipeline was made for ORCA 6, coming out soon. We have recently published an improved version of openCOSMO-RS that is based on ORCA 6, but should also work with 5.0.4 giving very similar results on arXiv: http://arxiv.org/abs/2407.03434

I need to give this some thought to find the best method to fix this.

**Comment by WangMM2** [comment]
oh great, thank you very much.

**Comment by simonmb** [comment]
@WangMM2, coud you confirm its working with the latest code? I just made a commit.
