### ISSUE TITLE
The xyzfile file is provided in the input, will the coordinates provided be used as the initial value during the calculation?

### ISSUE THREAD

**Issue by WangMM2** [TUHH-TVT/openCOSMO-RS_conformer_pipeline#8]
Hi~

When I calculated the choline chloride molecule, a reasonable molecular xyzfile was provided, but the file I gave did not seem to be read when I calculated. The initial structure automatically generated in the program is very unreasonable, resulting in failure to converge in subsequent calculations.

The contents of my fileinp are as follows:
          ChCl	C[N+](C)(C)CCO.[Cl-]	chcl.xyz	0

So, will the coordinates provided be used as the initial value during the calculation?
Hope to get your answer, thank you very much~

By the way, is it supported to generate multiple conformations of the molecule? Because when I do the command, I end up with what seems to be one molecular conformation, or maybe the molecules I'm testing are too small, right?

**Comment by simonmb** [comment]
Hi,
Thank you for the question. You are trying to calculate a orcacosmo file for an electrolyte. You can see that the provided smiles has a dot in it and the parts separated by the dot have a charge different from one. So probably the generated xyz file has the Cl anion quite far away from the choline cation. This cannot be handled by the code. 

You basically have two options depending on what you want to do with the result of the calculations. You can either generate a structure from a smiles where the ions are linked i.e. without the dot, or you can calculate the orcacosmo file for the ions separately. The first option should work fine, the second option probably needs some changes in the code as it was not developed with ions in mind.

**Comment by simonmb** [comment]
I will close the issue. If you have any other questions related to this topic you can reopen it.

**Comment by WangMM2** [comment]
Thank you very much.
I have tried to calculate it according to the second option in your reply.
